export const CHARACTER_STATES = {
  IDLE_STATE: 'IDLE_STATE',
  MOVE_STATE: 'MOVE_STATE',
  BOUNCE_MOVE_STATE: 'BOUNCE_MOVE_STATE',
  HURT_STATE: 'HURT_STATE',
  DEATH_STATE: 'DEATH_STATE',
  LIFT_STATE: 'LIFT_STATE',
  OPEN_CHEST_STATE: 'OPEN_CHEST_STATE',
  IDLE_HOLDING_STATE: 'IDLE_HOLDING_STATE',
  MOVE_HOLDING_STATE: 'MOVE_HOLDING_STATE',
  THROW_STATE: 'THROW_STATE',
} as const;
