export const ENABLE_LOGGING = false;
export const DEBUG_COLLISION_ALPHA = 0.6;

export const PLAYER_SPEED = 80;
export const PLAYER_INVULNERABLE_AFTER_HIT_DURATION = 1000;
export const PLAYER_HURT_PUSH_BACK_SPEED = 50;
export const PLAYER_START_MAX_HEALTH = 6;

export const ENEMY_SPIDER_SPEED = 80;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MIN = 500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_WAIT = 200;
export const ENEMY_SPIDER_HURT_PUSH_BACK_SPEED = 50;
export const ENEMY_SPIDER_MAX_HEALTH = 2;

export const ENEMY_WISP_SPEED = 50;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_X = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_Y = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_DURATION = 500;
export const ENEMY_WISP_MAX_HEALTH = 1;

export const HURT_PUSH_BACK_DELAY = 200;

export const THROW_ITEM_SPEED = 300;
export const THROW_ITEM_DELAY_BEFORE_CALLBACK = 200;

export const LIFT_ITEM_ANIMATION_DELAY = 0;
export const LIFT_ITEM_ANIMATION_DURATION = 250;
export const LIFT_ITEM_ANIMATION_ENABLE_DEBUGGING = false;

export const ROOM_TRANSITION_PLAYER_INTO_HALL_DURATION = 750;
export const ROOM_TRANSITION_PLAYER_INTO_HALL_DELAY = 250;
export const ROOM_TRANSITION_PLAYER_INTO_NEXT_ROOM_DURATION = 1000;
export const ROOM_TRANSITION_PLAYER_INTO_NEXT_ROOM_DELAY = 1200;
export const ROOM_TRANSITION_CAMERA_ANIMATION_DURATION = 1000;
export const ROOM_TRANSITION_CAMERA_ANIMATION_DELAY = 500;
